version: '3.8'

services:
  apiprocer:
    build:
      context: .
      args: #O JAR_FILE é usado dentro do Dockerfile
        JAR_FILE: build/libs/challenge-0.0.1-SNAPSHOT.jar
    ports:
      - "9000:9000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=challenge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5